### ISSUE TITLE
Research Python Social Auth and make a basic example

### ISSUE THREAD

**Issue by bens-schreiber** [bens-schreiber/pushapp-2023#6]
For this project, I have chosen to use Python Social Auth.
https://python-social-auth.readthedocs.io/en/latest/index.html

Python Social Auth is an OAuth2 protocol framework to aid us in logging in users with a google account.

Make a basic example where:
- An endpoint needs an authenticated user
- Another endpoint doesn't need an authenticated user
- We may log in via the Swagger "Authorize" button

Nothing needs to be saved in the database for this example to work.

Research and fully understand OAuth2 before moving in to Python Social Auth.

**Comment by KyanPepper** [comment]
LGTM
